# Documentation: https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'
services:
  jwt-creator:
    build: ./jwt-creator
    image: jwt-creator:v1
    container_name: jwt-creator
    ports:
      - "443"
    depends_on:
      cert-auth:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "443" ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 3s
    networks:
      clusternet:
        ipv4_address: 10.2.0.4
      internet:
        ipv4_address: 192.168.0.4

  jwt-verifier:
    build: ./jwt-verifier
    image: jwt-verifier:v1
    container_name: jwt-verifier
    cap_add:
      - NET_ADMIN
    ports:
      - "80"
    depends_on:
      cert-auth:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-A",
          "Healthbot/1.0",
          "-f",
          "http://localhost:80/jwt-verify/"
        ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 3s
    networks:
      clusternet:
        ipv4_address: 10.2.0.6
    command: sh -c "ip route del default && ip route add default via 10.2.0.5"

  cert-auth:
    build: ./cert-auth
    image: cert-auth:v1
    container_name: cert-auth
    cap_add:
      - NET_ADMIN
    ports:
      - "80"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-A",
          "Healthbot/1.0",
          "-f",
          "http://localhost:80/cert/"
        ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 3s
    networks:
      clusternet:
        ipv4_address: 10.2.0.7

  jwt-client:
    build: ./jwt-client
    image: jwt-client:v1
    container_name: jwt-client
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
    depends_on:
      cert-auth:
        condition: service_healthy
      jwt-creator:
        condition: service_healthy
      jwt-verifier:
        condition: service_healthy
      swan-carol:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-A",
          "Healthbot/1.0",
          "-f",
          "http://10.2.0.6:80/jwt-verify/"
        ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 3s
    networks:
      internet:
        ipv4_address: 192.168.0.2
      clientnet:
        ipv4_address: 10.1.0.2
    command: sh -c "ip route del default && ip route add default via 10.1.0.3"

  openssl-gen:
    image: openssl-gen:latest
    build: ./openssl-gen
    container_name: openssl-gen
    volumes:
      - ./strongswan:/mnt/strongswan

  swan-moon:
    build: ./strongswan
    image: alpine-strongswan:latest
    container_name: swan-moon
    depends_on:
      openssl-gen:
        condition: service_completed_successfully
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - ./strongswan/moon/etc-swanctl:/etc/swanctl
      - ./strongswan/moon/strongswan.conf:/etc/strongswan.conf
    networks:
      internet:
        ipv4_address: 192.168.0.5
      clusternet:
        ipv4_address: 10.2.0.5

  swan-carol:
    image: alpine-strongswan:latest
    container_name: swan-carol
    depends_on:
      swan-moon:
        condition: service_started
      openssl-gen:
        condition: service_completed_successfully
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    volumes:
      - ./strongswan/carol/etc-swanctl:/etc/swanctl
      - ./strongswan/carol/strongswan.conf:/etc/strongswan.conf
    healthcheck:
      test: [ "CMD", "ping", "-c", "2", "-W", "1", "10.2.0.5" ]
      interval: 1s
      timeout: 5s
      retries: 3
      start_period: 3s
    networks:
      internet:
        ipv4_address: 192.168.0.3
      clientnet:
        ipv4_address: 10.1.0.3

networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
  clientnet:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
  clusternet:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
